### ISSUE TITLE
pushbullet-types fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [tsani/pushbullet-hs#3]
```
pushbullet-types               > Building library for pushbullet-types-0.4.1.0..
pushbullet-types               > [ 1 of 12] Compiling Network.Pushbullet.Internal.Reflection
pushbullet-types               > [ 2 of 12] Compiling Network.Pushbullet.Types.Misc
pushbullet-types               > 
pushbullet-types               > /tmp/stack-38c1e2796976d64e/pushbullet-types-0.4.1.0/src/Network/Pushbullet/Types/Misc.hs:61:14: error:
pushbullet-types               >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
pushbullet-types               >                      with: H.HashMap k0 v0
pushbullet-types               >       Expected: H.HashMap k0 v0
pushbullet-types               >         Actual: Object
pushbullet-types               >     • In the first argument of ‘H.null’, namely ‘o’
pushbullet-types               >       In the expression: H.null o
pushbullet-types               >       In a stmt of a pattern guard for
pushbullet-types               >                      an equation for ‘parseJSON’:
pushbullet-types               >         H.null o
pushbullet-types               >    |
pushbullet-types               > 61 |     | H.null o = pure trivialObject
pushbullet-types               >    |              ^
```
